server:
  port: 42069

spring:
  application:
    name: dmr

  ai:
    ollama:
      base:
        url: http://localhost:11434

ai:
  models:
    qwen: qwen3.5:cloud
    gemma: gemma3:1b

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
    io:
      abhi:
        dmr:
          advisors: DEBUG